### ISSUE TITLE
current ruby in rvm not maintained my have problems

### ISSUE THREAD

**Issue by thefonso** [gmassanek/codemarks#123]
I just this error while attempting to install CM locally....

Install of ruby-1.9.3-p545 - #complete
WARNING: Please be aware that you just installed a ruby that is no longer maintained (2014-02-23), for a list of maintained rubies visit:

    http://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering

Please consider upgrading to ruby-2.1.1 which will have all of the latest security patches.

I'll continue with local install and document what i find. I'll then see if It will run fine with ruby-2.1.1

**Comment by gmassanek** [comment]
https://github.com/gmassanek/codemarks/pull/128
