### ISSUE TITLE
minor (but essential) typo in url

### ISSUE THREAD

**Issue by ousia** [gmassanek/codemarks#130]
@gmassanek, many thanks for _Codemarks_. It is really a useful tool.

I’m afraid I found the wrong url in your [profile page](https://github.com/gmassanek): `http://codemark.com/about` should read `http://codemarks.com/about`.

It is only a missing  _s_. But without it, we never reach home 😉.

**Comment by gmassanek** [comment]
Thanks! I've updated it.

And thanks for using codemarks! It was a personal pet project that I haven't really worked on in afew years but its still up and running. How did you find it?
